export interface Car {
  id: number;
  supplier_id: number;
  category_id: number;
  brand_id: number;
  branch_id: number;
  model: string;
  year: number;
  user_id: null;
  is_sold: number;
  is_booked: number;
  price: number;
  doors: number;
  acceleration: number;
  top_speed: number;
  fuel_efficiency: number;
  color: string;
  engine_type: string;
  engine_power: number;
  engine_cylinder: number;
  engine_cubic_capacity_type: number;
  transmission: string;
  features: string;
  performance: string;
  safety: string;
  is_available: number;
  main_image: string;
  images: string[];
}

// i have created 50 cars
export const CARS: Car[] = [
  {
    id: 1,
    supplier_id: 1,
    category_id: 1,
    brand_id: 1,
    branch_id: 1,
    model: 'Model S',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 79999,
    doors: 4,
    acceleration: 3.1,
    top_speed: 250,
    fuel_efficiency: 15,
    color: 'Red',
    engine_type: 'Electric',
    engine_power: 670,
    engine_cylinder: 0,
    engine_cubic_capacity_type: 0,
    transmission: 'Automatic',
    features: 'Autopilot, Leather Seats',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'model-s.jpg',
    images: ['model-s-1.jpg', 'model-s-2.jpg'],
  },
  {
    id: 2,
    supplier_id: 2,
    category_id: 2,
    brand_id: 2,
    branch_id: 1,
    model: 'Civic',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 1,
    price: 24999,
    doors: 4,
    acceleration: 8.2,
    top_speed: 200,
    fuel_efficiency: 30,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 158,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1800,
    transmission: 'Manual',
    features: 'Bluetooth, Backup Camera',
    performance: 'Standard',
    safety: '4-Star',
    is_available: 1,
    main_image: 'civic.jpg',
    images: ['civic-1.jpg', 'civic-2.jpg'],
  },
  {
    id: 3,
    supplier_id: 1,
    category_id: 3,
    brand_id: 3,
    branch_id: 2,
    model: 'Corolla',
    year: 2020,
    user_id: null,
    is_sold: 1,
    is_booked: 0,
    price: 21999,
    doors: 4,
    acceleration: 9.5,
    top_speed: 180,
    fuel_efficiency: 32,
    color: 'White',
    engine_type: 'Hybrid',
    engine_power: 121,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1800,
    transmission: 'Automatic',
    features: 'Lane Assist, Adaptive Cruise',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 0,
    main_image: 'corolla.jpg',
    images: ['corolla-1.jpg', 'corolla-2.jpg'],
  },
  {
    id: 4,
    supplier_id: 2,
    category_id: 1,
    brand_id: 4,
    branch_id: 2,
    model: 'Mustang',
    year: 2023,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 55999,
    doors: 2,
    acceleration: 4.2,
    top_speed: 250,
    fuel_efficiency: 12,
    color: 'Yellow',
    engine_type: 'Petrol',
    engine_power: 450,
    engine_cylinder: 8,
    engine_cubic_capacity_type: 5000,
    transmission: 'Manual',
    features: 'Convertible, Sport Mode',
    performance: 'High',
    safety: '4-Star',
    is_available: 1,
    main_image: 'mustang.jpg',
    images: ['mustang-1.jpg', 'mustang-2.jpg'],
  },
  {
    id: 5,
    supplier_id: 3,
    category_id: 2,
    brand_id: 5,
    branch_id: 3,
    model: 'Camry',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 27999,
    doors: 4,
    acceleration: 7.6,
    top_speed: 210,
    fuel_efficiency: 28,
    color: 'Black',
    engine_type: 'Hybrid',
    engine_power: 208,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'Heated Seats, Sunroof',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'camry.jpg',
    images: ['camry-1.jpg', 'camry-2.jpg'],
  },
  {
    id: 6,
    supplier_id: 1,
    category_id: 3,
    brand_id: 6,
    branch_id: 1,
    model: 'Accord',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 26999,
    doors: 4,
    acceleration: 7.2,
    top_speed: 205,
    fuel_efficiency: 27,
    color: 'Silver',
    engine_type: 'Petrol',
    engine_power: 192,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1500,
    transmission: 'Automatic',
    features: 'Remote Start, Apple CarPlay',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'accord.jpg',
    images: ['accord-1.jpg', 'accord-2.jpg'],
  },
  {
    id: 7,
    supplier_id: 2,
    category_id: 1,
    brand_id: 7,
    branch_id: 2,
    model: 'A4',
    year: 2023,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 39999,
    doors: 4,
    acceleration: 6.1,
    top_speed: 240,
    fuel_efficiency: 25,
    color: 'Gray',
    engine_type: 'Petrol',
    engine_power: 201,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Virtual Cockpit, LED Headlights',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'a4.jpg',
    images: ['a4-1.jpg', 'a4-2.jpg'],
  },
  {
    id: 8,
    supplier_id: 3,
    category_id: 2,
    brand_id: 8,
    branch_id: 3,
    model: '3 Series',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 42999,
    doors: 4,
    acceleration: 5.6,
    top_speed: 250,
    fuel_efficiency: 24,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 255,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Navigation, Parking Sensors',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: '3series.jpg',
    images: ['3series-1.jpg', '3series-2.jpg'],
  },
  {
    id: 9,
    supplier_id: 1,
    category_id: 3,
    brand_id: 9,
    branch_id: 1,
    model: 'C-Class',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 45999,
    doors: 4,
    acceleration: 6.0,
    top_speed: 245,
    fuel_efficiency: 23,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 255,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Ambient Lighting, Sunroof',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'cclass.jpg',
    images: ['cclass-1.jpg', 'cclass-2.jpg'],
  },
  {
    id: 10,
    supplier_id: 2,
    category_id: 1,
    brand_id: 10,
    branch_id: 2,
    model: 'Altima',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 23999,
    doors: 4,
    acceleration: 8.0,
    top_speed: 210,
    fuel_efficiency: 28,
    color: 'Black',
    engine_type: 'Petrol',
    engine_power: 188,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'Blind Spot Monitor, Remote Start',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'altima.jpg',
    images: ['altima-1.jpg', 'altima-2.jpg'],
  },
  {
    id: 11,
    supplier_id: 3,
    category_id: 2,
    brand_id: 11,
    branch_id: 3,
    model: 'Mazda3',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 22999,
    doors: 4,
    acceleration: 8.1,
    top_speed: 200,
    fuel_efficiency: 29,
    color: 'Red',
    engine_type: 'Petrol',
    engine_power: 186,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Heads-Up Display, Bose Audio',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'mazda3.jpg',
    images: ['mazda3-1.jpg', 'mazda3-2.jpg'],
  },
  {
    id: 12,
    supplier_id: 1,
    category_id: 3,
    brand_id: 12,
    branch_id: 1,
    model: 'Impreza',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 21999,
    doors: 4,
    acceleration: 9.0,
    top_speed: 190,
    fuel_efficiency: 27,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 152,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, EyeSight Safety',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'impreza.jpg',
    images: ['impreza-1.jpg', 'impreza-2.jpg'],
  },
  {
    id: 13,
    supplier_id: 2,
    category_id: 1,
    brand_id: 13,
    branch_id: 2,
    model: 'Golf',
    year: 2023,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 24999,
    doors: 4,
    acceleration: 7.8,
    top_speed: 210,
    fuel_efficiency: 31,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 147,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1400,
    transmission: 'Automatic',
    features: 'Digital Cockpit, Adaptive Cruise',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'golf.jpg',
    images: ['golf-1.jpg', 'golf-2.jpg'],
  },
  {
    id: 14,
    supplier_id: 3,
    category_id: 2,
    brand_id: 14,
    branch_id: 3,
    model: 'Elantra',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 20999,
    doors: 4,
    acceleration: 8.5,
    top_speed: 195,
    fuel_efficiency: 33,
    color: 'Gray',
    engine_type: 'Petrol',
    engine_power: 147,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1600,
    transmission: 'Automatic',
    features: 'Wireless CarPlay, Lane Keep Assist',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'elantra.jpg',
    images: ['elantra-1.jpg', 'elantra-2.jpg'],
  },
  {
    id: 15,
    supplier_id: 1,
    category_id: 3,
    brand_id: 15,
    branch_id: 1,
    model: 'Jetta',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 21999,
    doors: 4,
    acceleration: 8.0,
    top_speed: 200,
    fuel_efficiency: 30,
    color: 'Black',
    engine_type: 'Petrol',
    engine_power: 147,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1400,
    transmission: 'Automatic',
    features: 'Blind Spot Monitor, Heated Seats',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'jetta.jpg',
    images: ['jetta-1.jpg', 'jetta-2.jpg'],
  },
  {
    id: 16,
    supplier_id: 2,
    category_id: 1,
    brand_id: 16,
    branch_id: 2,
    model: 'Fusion',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 22999,
    doors: 4,
    acceleration: 8.3,
    top_speed: 205,
    fuel_efficiency: 27,
    color: 'Silver',
    engine_type: 'Hybrid',
    engine_power: 188,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Remote Start, Apple CarPlay',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'fusion.jpg',
    images: ['fusion-1.jpg', 'fusion-2.jpg'],
  },
  {
    id: 17,
    supplier_id: 3,
    category_id: 2,
    brand_id: 17,
    branch_id: 3,
    model: 'Sonata',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 23999,
    doors: 4,
    acceleration: 7.9,
    top_speed: 210,
    fuel_efficiency: 28,
    color: 'Blue',
    engine_type: 'Hybrid',
    engine_power: 192,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Panoramic Sunroof, Bose Audio',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'sonata.jpg',
    images: ['sonata-1.jpg', 'sonata-2.jpg'],
  },
  {
    id: 18,
    supplier_id: 1,
    category_id: 3,
    brand_id: 18,
    branch_id: 1,
    model: 'Malibu',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 21999,
    doors: 4,
    acceleration: 8.5,
    top_speed: 200,
    fuel_efficiency: 29,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 160,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1500,
    transmission: 'Automatic',
    features: 'WiFi Hotspot, Remote Start',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'malibu.jpg',
    images: ['malibu-1.jpg', 'malibu-2.jpg'],
  },
  {
    id: 19,
    supplier_id: 2,
    category_id: 1,
    brand_id: 19,
    branch_id: 2,
    model: 'Passat',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 22999,
    doors: 4,
    acceleration: 8.0,
    top_speed: 210,
    fuel_efficiency: 27,
    color: 'Gray',
    engine_type: 'Petrol',
    engine_power: 174,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1800,
    transmission: 'Automatic',
    features: 'Adaptive Cruise, Heated Seats',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'passat.jpg',
    images: ['passat-1.jpg', 'passat-2.jpg'],
  },
  {
    id: 20,
    supplier_id: 3,
    category_id: 2,
    brand_id: 20,
    branch_id: 3,
    model: 'Sentra',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 20999,
    doors: 4,
    acceleration: 9.2,
    top_speed: 190,
    fuel_efficiency: 33,
    color: 'Black',
    engine_type: 'Petrol',
    engine_power: 149,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1600,
    transmission: 'Automatic',
    features: 'Blind Spot Monitor, Apple CarPlay',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'sentra.jpg',
    images: ['sentra-1.jpg', 'sentra-2.jpg'],
  },
  {
    id: 21,
    supplier_id: 1,
    category_id: 3,
    brand_id: 21,
    branch_id: 1,
    model: 'Prius',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 24999,
    doors: 4,
    acceleration: 10.5,
    top_speed: 180,
    fuel_efficiency: 50,
    color: 'Silver',
    engine_type: 'Hybrid',
    engine_power: 121,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1800,
    transmission: 'Automatic',
    features: 'Lane Keep Assist, Adaptive Cruise',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'prius.jpg',
    images: ['prius-1.jpg', 'prius-2.jpg'],
  },
  {
    id: 22,
    supplier_id: 2,
    category_id: 1,
    brand_id: 22,
    branch_id: 2,
    model: 'Focus',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 19999,
    doors: 4,
    acceleration: 8.7,
    top_speed: 195,
    fuel_efficiency: 32,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 160,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1600,
    transmission: 'Manual',
    features: 'Rear Camera, Bluetooth',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'focus.jpg',
    images: ['focus-1.jpg', 'focus-2.jpg'],
  },
  {
    id: 23,
    supplier_id: 3,
    category_id: 2,
    brand_id: 23,
    branch_id: 3,
    model: 'Rio',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 17999,
    doors: 4,
    acceleration: 10.2,
    top_speed: 180,
    fuel_efficiency: 36,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 120,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1400,
    transmission: 'Automatic',
    features: 'Apple CarPlay, Rear Camera',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'rio.jpg',
    images: ['rio-1.jpg', 'rio-2.jpg'],
  },
  {
    id: 24,
    supplier_id: 1,
    category_id: 3,
    brand_id: 24,
    branch_id: 1,
    model: 'Yaris',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 18999,
    doors: 4,
    acceleration: 10.0,
    top_speed: 175,
    fuel_efficiency: 35,
    color: 'Red',
    engine_type: 'Petrol',
    engine_power: 106,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1300,
    transmission: 'Automatic',
    features: 'Bluetooth, Lane Departure Alert',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'yaris.jpg',
    images: ['yaris-1.jpg', 'yaris-2.jpg'],
  },
  {
    id: 25,
    supplier_id: 2,
    category_id: 1,
    brand_id: 25,
    branch_id: 2,
    model: 'Fiesta',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 16999,
    doors: 4,
    acceleration: 9.9,
    top_speed: 170,
    fuel_efficiency: 34,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 120,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1400,
    transmission: 'Manual',
    features: 'SYNC, Rear Camera',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'fiesta.jpg',
    images: ['fiesta-1.jpg', 'fiesta-2.jpg'],
  },
  {
    id: 26,
    supplier_id: 3,
    category_id: 2,
    brand_id: 26,
    branch_id: 3,
    model: 'Spark',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 15999,
    doors: 4,
    acceleration: 11.0,
    top_speed: 160,
    fuel_efficiency: 38,
    color: 'Silver',
    engine_type: 'Petrol',
    engine_power: 98,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1200,
    transmission: 'Automatic',
    features: 'Apple CarPlay, Rear Camera',
    performance: 'Standard',
    safety: '4-Star',
    is_available: 1,
    main_image: 'spark.jpg',
    images: ['spark-1.jpg', 'spark-2.jpg'],
  },
  {
    id: 27,
    supplier_id: 1,
    category_id: 3,
    brand_id: 27,
    branch_id: 1,
    model: 'A3',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 32999,
    doors: 4,
    acceleration: 6.6,
    top_speed: 235,
    fuel_efficiency: 27,
    color: 'Black',
    engine_type: 'Petrol',
    engine_power: 184,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1400,
    transmission: 'Automatic',
    features: 'Virtual Cockpit, LED Headlights',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'a3.jpg',
    images: ['a3-1.jpg', 'a3-2.jpg'],
  },
  {
    id: 28,
    supplier_id: 2,
    category_id: 1,
    brand_id: 28,
    branch_id: 2,
    model: 'CLA',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 35999,
    doors: 4,
    acceleration: 6.3,
    top_speed: 240,
    fuel_efficiency: 26,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 221,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'MBUX, Panoramic Sunroof',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'cla.jpg',
    images: ['cla-1.jpg', 'cla-2.jpg'],
  },
  {
    id: 29,
    supplier_id: 3,
    category_id: 2,
    brand_id: 29,
    branch_id: 3,
    model: 'Qashqai',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 27999,
    doors: 4,
    acceleration: 9.5,
    top_speed: 190,
    fuel_efficiency: 34,
    color: 'Gray',
    engine_type: 'Petrol',
    engine_power: 140,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1600,
    transmission: 'Automatic',
    features: '360 Camera, ProPILOT',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'qashqai.jpg',
    images: ['qashqai-1.jpg', 'qashqai-2.jpg'],
  },
  {
    id: 30,
    supplier_id: 1,
    category_id: 3,
    brand_id: 30,
    branch_id: 1,
    model: 'CX-5',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 30999,
    doors: 4,
    acceleration: 8.7,
    top_speed: 200,
    fuel_efficiency: 28,
    color: 'Red',
    engine_type: 'Petrol',
    engine_power: 187,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'AWD, Bose Audio',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'cx5.jpg',
    images: ['cx5-1.jpg', 'cx5-2.jpg'],
  },
  {
    id: 31,
    supplier_id: 2,
    category_id: 1,
    brand_id: 31,
    branch_id: 2,
    model: 'Tucson',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 28999,
    doors: 4,
    acceleration: 9.1,
    top_speed: 190,
    fuel_efficiency: 29,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 161,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'Blind Spot Monitor, Lane Keep Assist',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'tucson.jpg',
    images: ['tucson-1.jpg', 'tucson-2.jpg'],
  },
  {
    id: 32,
    supplier_id: 3,
    category_id: 2,
    brand_id: 32,
    branch_id: 3,
    model: 'CR-V',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 31999,
    doors: 4,
    acceleration: 7.8,
    top_speed: 210,
    fuel_efficiency: 27,
    color: 'White',
    engine_type: 'Hybrid',
    engine_power: 212,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Apple CarPlay',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'crv.jpg',
    images: ['crv-1.jpg', 'crv-2.jpg'],
  },
  {
    id: 33,
    supplier_id: 1,
    category_id: 3,
    brand_id: 33,
    branch_id: 1,
    model: 'RAV4',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 32999,
    doors: 4,
    acceleration: 8.1,
    top_speed: 200,
    fuel_efficiency: 30,
    color: 'Silver',
    engine_type: 'Hybrid',
    engine_power: 219,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'AWD, Lane Keep Assist',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'rav4.jpg',
    images: ['rav4-1.jpg', 'rav4-2.jpg'],
  },
  {
    id: 34,
    supplier_id: 2,
    category_id: 1,
    brand_id: 34,
    branch_id: 2,
    model: 'Escape',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 27999,
    doors: 4,
    acceleration: 8.4,
    top_speed: 195,
    fuel_efficiency: 28,
    color: 'Black',
    engine_type: 'Hybrid',
    engine_power: 200,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Apple CarPlay',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'escape.jpg',
    images: ['escape-1.jpg', 'escape-2.jpg'],
  },
  {
    id: 35,
    supplier_id: 3,
    category_id: 2,
    brand_id: 35,
    branch_id: 3,
    model: 'Kona',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 25999,
    doors: 4,
    acceleration: 8.6,
    top_speed: 190,
    fuel_efficiency: 32,
    color: 'Blue',
    engine_type: 'Electric',
    engine_power: 201,
    engine_cylinder: 0,
    engine_cubic_capacity_type: 0,
    transmission: 'Automatic',
    features: 'Wireless CarPlay, Lane Keep Assist',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'kona.jpg',
    images: ['kona-1.jpg', 'kona-2.jpg'],
  },
  {
    id: 36,
    supplier_id: 1,
    category_id: 3,
    brand_id: 36,
    branch_id: 1,
    model: 'CX-30',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 26999,
    doors: 4,
    acceleration: 8.2,
    top_speed: 195,
    fuel_efficiency: 28,
    color: 'Red',
    engine_type: 'Petrol',
    engine_power: 186,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Bose Audio',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'cx30.jpg',
    images: ['cx30-1.jpg', 'cx30-2.jpg'],
  },
  {
    id: 37,
    supplier_id: 2,
    category_id: 1,
    brand_id: 37,
    branch_id: 2,
    model: 'Sportage',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 27999,
    doors: 4,
    acceleration: 8.8,
    top_speed: 190,
    fuel_efficiency: 27,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 181,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Lane Keep Assist',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'sportage.jpg',
    images: ['sportage-1.jpg', 'sportage-2.jpg'],
  },
  {
    id: 38,
    supplier_id: 3,
    category_id: 2,
    brand_id: 38,
    branch_id: 3,
    model: 'Rogue',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 28999,
    doors: 4,
    acceleration: 8.5,
    top_speed: 190,
    fuel_efficiency: 29,
    color: 'Gray',
    engine_type: 'Petrol',
    engine_power: 181,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'AWD, ProPILOT',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'rogue.jpg',
    images: ['rogue-1.jpg', 'rogue-2.jpg'],
  },
  {
    id: 39,
    supplier_id: 1,
    category_id: 3,
    brand_id: 39,
    branch_id: 1,
    model: 'Forester',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 29999,
    doors: 4,
    acceleration: 8.7,
    top_speed: 190,
    fuel_efficiency: 28,
    color: 'Silver',
    engine_type: 'Petrol',
    engine_power: 182,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'AWD, EyeSight Safety',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'forester.jpg',
    images: ['forester-1.jpg', 'forester-2.jpg'],
  },
  {
    id: 40,
    supplier_id: 2,
    category_id: 1,
    brand_id: 40,
    branch_id: 2,
    model: 'Outback',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 31999,
    doors: 4,
    acceleration: 8.5,
    top_speed: 190,
    fuel_efficiency: 27,
    color: 'Green',
    engine_type: 'Petrol',
    engine_power: 182,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2500,
    transmission: 'Automatic',
    features: 'AWD, EyeSight Safety',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'outback.jpg',
    images: ['outback-1.jpg', 'outback-2.jpg'],
  },
  {
    id: 41,
    supplier_id: 3,
    category_id: 2,
    brand_id: 41,
    branch_id: 3,
    model: 'X1',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 36999,
    doors: 4,
    acceleration: 6.6,
    top_speed: 230,
    fuel_efficiency: 26,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 228,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Navigation',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'x1.jpg',
    images: ['x1-1.jpg', 'x1-2.jpg'],
  },
  {
    id: 42,
    supplier_id: 1,
    category_id: 3,
    brand_id: 42,
    branch_id: 1,
    model: 'GLA',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 37999,
    doors: 4,
    acceleration: 6.8,
    top_speed: 225,
    fuel_efficiency: 25,
    color: 'Black',
    engine_type: 'Petrol',
    engine_power: 221,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, MBUX',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'gla.jpg',
    images: ['gla-1.jpg', 'gla-2.jpg'],
  },
  {
    id: 43,
    supplier_id: 2,
    category_id: 1,
    brand_id: 43,
    branch_id: 2,
    model: 'Q3',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 38999,
    doors: 4,
    acceleration: 7.0,
    top_speed: 220,
    fuel_efficiency: 24,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 228,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Virtual Cockpit',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'q3.jpg',
    images: ['q3-1.jpg', 'q3-2.jpg'],
  },
  {
    id: 44,
    supplier_id: 3,
    category_id: 2,
    brand_id: 44,
    branch_id: 3,
    model: 'XC40',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 40999,
    doors: 4,
    acceleration: 6.2,
    top_speed: 210,
    fuel_efficiency: 23,
    color: 'Gray',
    engine_type: 'Hybrid',
    engine_power: 248,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 2000,
    transmission: 'Automatic',
    features: 'AWD, Pilot Assist',
    performance: 'High',
    safety: '5-Star',
    is_available: 1,
    main_image: 'xc40.jpg',
    images: ['xc40-1.jpg', 'xc40-2.jpg'],
  },
  {
    id: 45,
    supplier_id: 1,
    category_id: 3,
    brand_id: 45,
    branch_id: 1,
    model: 'T-Roc',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 29999,
    doors: 4,
    acceleration: 8.4,
    top_speed: 205,
    fuel_efficiency: 29,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 150,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1500,
    transmission: 'Automatic',
    features: 'AWD, Digital Cockpit',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'troc.jpg',
    images: ['troc-1.jpg', 'troc-2.jpg'],
  },
  {
    id: 46,
    supplier_id: 2,
    category_id: 1,
    brand_id: 46,
    branch_id: 2,
    model: 'HR-V',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 25999,
    doors: 4,
    acceleration: 9.3,
    top_speed: 190,
    fuel_efficiency: 31,
    color: 'Silver',
    engine_type: 'Petrol',
    engine_power: 141,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1800,
    transmission: 'Automatic',
    features: 'AWD, Magic Seats',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'hrv.jpg',
    images: ['hrv-1.jpg', 'hrv-2.jpg'],
  },
  {
    id: 47,
    supplier_id: 3,
    category_id: 2,
    brand_id: 47,
    branch_id: 3,
    model: 'Kicks',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 21999,
    doors: 4,
    acceleration: 9.7,
    top_speed: 180,
    fuel_efficiency: 33,
    color: 'Blue',
    engine_type: 'Petrol',
    engine_power: 122,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1600,
    transmission: 'Automatic',
    features: 'Apple CarPlay, Rear Camera',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'kicks.jpg',
    images: ['kicks-1.jpg', 'kicks-2.jpg'],
  },
  {
    id: 48,
    supplier_id: 1,
    category_id: 3,
    brand_id: 48,
    branch_id: 1,
    model: 'EcoSport',
    year: 2021,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 20999,
    doors: 4,
    acceleration: 10.0,
    top_speed: 175,
    fuel_efficiency: 30,
    color: 'Red',
    engine_type: 'Petrol',
    engine_power: 123,
    engine_cylinder: 3,
    engine_cubic_capacity_type: 1000,
    transmission: 'Automatic',
    features: 'AWD, SYNC',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'ecosport.jpg',
    images: ['ecosport-1.jpg', 'ecosport-2.jpg'],
  },
  {
    id: 49,
    supplier_id: 2,
    category_id: 1,
    brand_id: 49,
    branch_id: 2,
    model: 'Venue',
    year: 2020,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 19999,
    doors: 4,
    acceleration: 10.5,
    top_speed: 170,
    fuel_efficiency: 33,
    color: 'White',
    engine_type: 'Petrol',
    engine_power: 121,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1200,
    transmission: 'Automatic',
    features: 'Wireless CarPlay, Rear Camera',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'venue.jpg',
    images: ['venue-1.jpg', 'venue-2.jpg'],
  },
  {
    id: 50,
    supplier_id: 3,
    category_id: 2,
    brand_id: 50,
    branch_id: 3,
    model: 'Seltos',
    year: 2022,
    user_id: null,
    is_sold: 0,
    is_booked: 0,
    price: 22999,
    doors: 4,
    acceleration: 9.2,
    top_speed: 180,
    fuel_efficiency: 32,
    color: 'Gray',
    engine_type: 'Petrol',
    engine_power: 146,
    engine_cylinder: 4,
    engine_cubic_capacity_type: 1600,
    transmission: 'Automatic',
    features: 'AWD, Bose Audio',
    performance: 'Standard',
    safety: '5-Star',
    is_available: 1,
    main_image: 'seltos.jpg',
    images: ['seltos-1.jpg', 'seltos-2.jpg'],
  },
];
